version: "3.8"
services:
  frontend:
    image: mimicpredictors/frontend
    build:
      context: ./services/frontend
    depends_on:
      - backend

  backend:
    image: mimicpredictors/backend
    build:
      context: ./services/backend
    environment:
      GRPC_HOST: tf-serving
      GRPC_PORT: 5000
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_DATABASE: mimic-predictors-samples
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - tf-serving
      - mongodb

  mongodb:
    image: mimicpredictors/mongodb
    build:
      context: ./services/mongodb
    environment:
      MONGO_INITDB_DATABASE: mimic-predictors-samples
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root # TODO: put in secrets file
    volumes:
      - mongodb_data:/data/db

  tf-serving:
    image: mimicpredictors/tf-serving
    build:
      context: ./services/tf-serving
    command:
      - "--model_config_file=/models/model.config"
      - "--port=5000"
      - "--rest_api_port=0"

volumes:
  mongodb_data:
