version: "3.8"
services:
  frontend:
    image: hitmimicpredictors/frontend
    build:
      context: ./services/frontend

  backend:
    image: hitmimicpredictors/backend
    build:
      context: ./services/backend
      args:
        PIP_MIRROR: https://mirrors.aliyun.com/pypi/simple/
    environment:
      GRPC_HOST: tf-serving
      GRPC_PORT: 9090
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_DATABASE: mimic-predictors-samples
      DB_USER: root
      DB_PASSWORD: root

  mongodb:
    image: hitmimicpredictors/mongodb
    build:
      context: ./services/mongodb
    environment:
      MONGO_INITDB_DATABASE: mimic-predictors-samples
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root # TODO: put in secrets file
    volumes:
      - mongodb_data:/data/db

  tf-serving:
    image: hitmimicpredictors/tf-serving
    build:
      context: ./services/tf-serving
    command:
      - "--model_config_file=/models/model.config"
      - "--port=9090"
      - "--rest_api_port=0"

volumes:
  mongodb_data:
