version: "3.8"

services:
  traefik:
    deploy:
      placement:
        constraints:
          - node.role == manager

  frontend:
    deploy:
      replicas: 18
      placement:
        constraints:
          - node.role != manager
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

  backend:
    deploy:
      replicas: 18
      placement:
        constraints:
          - node.role != manager
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

  tf-serving:
    deploy:
      replicas: 18
      placement:
        constraints:
          - node.role != manager
      update_config:
        parallelism: 2
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
