version: "3.8"
services:
  api-server:
    build:
      context: ./services/api-server
      dockerfile: Dockerfile.fastapi
    restart: always
    environment:
      GRPC_HOST: tf-serving
      GRPC_PORT: 5000
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_DATABASE: mimic-predictors-samples
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - 5050:80
    depends_on:
      - tf-serving
      - mongodb

  mongodb:
    build:
      context: ./services/mongodb
      dockerfile: Dockerfile.db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mimic-predictors-samples
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root # TODO: put in secrets file
    expose:
      - 27017

  tf-serving:
    build:
      context: ./services/tf-serving
      dockerfile: Dockerfile.tf
    restart: always
    command:
      - "--model_config_file=/models/model.config"
      - "--port=5000"
      - "--rest_api_port=0"
    expose:
      - 5000
