version: "3.8"
services:
  api-server:
    build:
      context: ./services/api-server
      dockerfile: Dockerfile.fastapi
    environment:
      GRPC_HOST: tf-serving
      GRPC_PORT: 5000
    ports:
      - "5050:80"
    depends_on:
      - tf-serving

  tf-serving:
    build:
      context: ./services/tf-serving
      dockerfile: Dockerfile.tf
    command:
      - "--model_config_file=/models/model.config"
      - "--port=5000"
      - "--rest_api_port=0"
    expose:
      - "5000"
